# Operations between Operator and PauliString and between PauliString and PauliString
# ======================================================================================

# Operations between PauliString and PauliString
# ----------------------------------------------------

Base.:+(s1::T, s2::T) where {T<:PauliString} = Operator(qubitlength(s1)) + s1 + s2
Base.:-(s1::T, s2::T) where {T<:PauliString} = Operator(qubitlength(s1)) + s1 - s2

"""
    Base.cis(p::PauliString)

Return the operator `exp(im * P)` where `P` is the matrix corresponding
to the single Pauli string `p`. The result is an `Operator` acting on the
same number of qubits as `p`.
"""
function Base.cis(p::PauliString)
    I_p = one(typeof(p))
    OpI = Operator(I_p)
    OpP = Operator(p)
    s, c = sincos(1.0)
    return c * OpI + (1im * s) * OpP
end

"""
    Base.exp(p::PauliString)

Return the operator `exp(P)` where `P` is the matrix corresponding
to the single Pauli string `p`. The result is an `Operator` acting on the
same number of qubits as `p`.
"""
function Base.exp(p::PauliString)
    I_p = one(typeof(p))
    OpI = Operator(I_p)
    OpP = Operator(p)
    ch = cosh(1.0)
    sh = sinh(1.0)
    return ch * OpI + sh * OpP
end

"""
    pauli_rotation(G::PauliString, P::PauliString, theta::Real)

Heisenberg-picture action of a Pauli rotation generated by `G` on a single
Pauli string `P`, corresponding to

    RG(theta)[P] = exp(1im * theta * G / 2) * P * exp(-1im * theta * G / 2)

as in Eqs. (13)–(14) of https://arxiv.org/pdf/2505.21606.
If `P` commutes with `G`, this returns `P` as an `Operator`. Otherwise it
returns the 2-branching combination `cos(theta) P + sin(theta) P′` as an
`Operator`, where `P′ = (im/2) * [G, P]` is constructed from the commutator.
"""
function pauli_rotation(G::PauliString, P::PauliString, theta::Real)
    stheta, ctheta = sincos(theta)
    C,k = commutator(G, P)
    if k == 0                   # commuting case
        return Operator(P)
    end
    c1 = (1.0im)^ycount(G)
    c2 = (1.0im)^ycount(P)
    return Operator([P, C], [ctheta*c2, (1im * stheta / 2) * k*c1*c2])
end


# Operations between PauliStringTS and PauliStringTS
# ----------------------------------------------------

Base.:+(s1::T, s2::T) where {T<:PauliStringTS} = OperatorTS(s1) + s2
Base.:-(s1::T, s2::T) where {T<:PauliStringTS} = OperatorTS(s1) - s2


# Operations between PauliString and scalar
# -----------------------------------------

Base.:*(c::Number, p::PauliString) = Operator(p) * c
Base.:*(p::PauliString, c::Number) = c * p
Base.:/(p::PauliString, c::Number) = (1 / c) * p
Base.:+(c::Number, p::PauliString) = Operator(p) + c
Base.:+(p::PauliString, c::Number) = c + p
Base.:-(c::Number, p::PauliString) = c - Operator(p)
Base.:-(p::PauliString, c::Number) = Operator(p) - c

# Operations between PauliStringTS and scalar
# -----------------------------------------
Base.:*(c::Number, p::PauliStringTS) = OperatorTS(p) * c
Base.:*(p::PauliStringTS, c::Number) = c * p
Base.:/(p::PauliStringTS, c::Number) = (1 / c) * p
Base.:+(c::Number, p::PauliStringTS) = OperatorTS(p) + c
Base.:+(p::PauliStringTS, c::Number) = c + p
Base.:-(c::Number, p::PauliStringTS) = c - OperatorTS(p)
Base.:-(p::PauliStringTS, c::Number) = OperatorTS(p) - c
