"""
    f_unitary(H, O, s, ħ) -> Ȯ

Time-derivative of `O` generated by `H`, i.e. ``Ȯ = (s/ħ) ⋅ \\[H, O\\]``.
"""
f_unitary(H, O, s, hbar) = commutator(H, O, s / hbar)


"""
    rk4(H::AbstractOperator, O::AbstractOperator, dt::Real; hbar::Real=1, heisenberg=true, truncation::Function=copy, f=f_unitary)

Single step of Runge–Kutta-4 with time independant Hamiltonian.
Returns O(t+dt).
`truncation` : function that takes an operator and returns a truncated version of it. By default it is `identity` (no truncation).
"""
function rk4(
        H::AbstractOperator, O::AbstractOperator, dt::Real;
        hbar::Real = 1, heisenberg = true, truncation::Function = identity, f = f_unitary
    )
    s = heisenberg ? 1im : -1im

    k₁ = truncation(f(H, O, s, hbar))
    Oₜ₊₁ = add(O, k₁, dt / 6)

    k₂ = truncation(f(H, add!(k₁, O, true, dt / 2), s, hbar))
    Oₜ₊₁ = add!(Oₜ₊₁, k₂, dt / 3)

    k₃ = truncation(f(H, add!(k₂, O, true, dt / 2), s, hbar))
    Oₜ₊₁ = add!(Oₜ₊₁, k₃, dt / 3)

    k₄ = truncation(f(H, add!(k₃, O, true, dt), s, hbar))
    Oₜ₊₁ = add!(Oₜ₊₁, k₄, dt / 6)

    return Oₜ₊₁
end


"""
    dopri5(H::AbstractOperator, O::AbstractOperator, dt::Real; hbar::Real=1, heisenberg=true, truncation::Function=identity, f=f_unitary)

Single step of Dormand–Prince-5 with time independant Hamiltonian.
Returns O(t+dt).
`truncation` : function that takes an operator and returns a truncated version of it. By default it is `identity` (no truncation).
"""
function dopri5(
        H::AbstractOperator, O::AbstractOperator, dt::Real;
        hbar::Real = 1, heisenberg = true, truncation::Function = identity, f = f_unitary
    )
    s = heisenberg ? 1im : -1im
    a21 = 1 / 5
    a31, a32 = 3 / 40, 9 / 40
    a41, a42, a43 = 44 / 45, -56 / 15, 32 / 9
    a51, a52, a53, a54 = 19372 / 6561, -25360 / 2187, 64448 / 6561, -212 / 729
    a61, a62, a63, a64, a65 = 9017 / 3168, -355 / 33, 46732 / 5247, 49 / 176, -5103 / 18656
    b1, b3, b4, b5, b6 = 35 / 384, 500 / 1113, 125 / 192, -2187 / 6784, 11 / 84

    k1 = truncation(f(H, O, s, hbar))
    Oₜ₊₁ = add(O, k1, dt * b1)

    Y = add(O, k1, dt * a21)
    k2 = truncation(f(H, Y, s, hbar))

    Y = add(O, k1, dt * a31); add!(Y, k2, dt * a32)
    k3 = truncation(f(H, Y, s, hbar))
    Oₜ₊₁ = add!(Oₜ₊₁, k3, dt * b3)

    Y = add(O, k1, dt * a41); add!(Y, k2, dt * a42); add!(Y, k3, dt * a43)
    k4 = truncation(f(H, Y, s, hbar))
    Oₜ₊₁ = add!(Oₜ₊₁, k4, dt * b4)

    Y = add(O, k1, dt * a51); add!(Y, k2, dt * a52); add!(Y, k3, dt * a53); add!(Y, k4, dt * a54)
    k5 = truncation(f(H, Y, s, hbar))
    Oₜ₊₁ = add!(Oₜ₊₁, k5, dt * b5)

    Y = add(O, k1, dt * a61); add!(Y, k2, dt * a62); add!(Y, k3, dt * a63); add!(Y, k4, dt * a64); add!(Y, k5, dt * a65)
    k6 = truncation(f(H, Y, s, hbar))
    Oₜ₊₁ = add!(Oₜ₊₁, k6, dt * b6)

    return Oₜ₊₁
end


"""
    rk4(H::Function, O::AbstractOperator, dt::Real, t::Real; hbar::Real=1, heisenberg=true, truncation::Function=identity, f=f_unitary)

Single step of Runge–Kutta-4 with time dependant Hamiltonian.
Returns O(t+dt).
`H` is a function that takes time `t` and returns the Hamiltonian at that time.
`truncation` : function that takes an operator and returns a truncated version of it. By default it is `identity` (no truncation).
"""
function rk4(H::Function, O::AbstractOperator, dt::Real, t::Real; hbar::Real=1, heisenberg=true, truncation::Function=identity, f=f_unitary)
    return rk4(H(t), O, dt; hbar=hbar, heisenberg=heisenberg, truncation=truncation, f=f)
end



function f_lindblad(H, O, s, hbar, L, gamma)
    Odot = f_unitary(H, O, s, hbar)
    for i in 1:length(L)
        if s == 1im
            A = L[i]' * O * L[i]
        elseif s == -1im
            A = L[i] * O * L[i]'
        else
            throw(ArgumentError("s should be 1im or -1im"))
        end
        LL = L[i]' * L[i]
        Odot += gamma[i] * (A - anticommutator(LL, O) / 2)
    end
    return Odot
end




"""
    rk4_lindblad(H::AbstractOperator, O::AbstractOperator, dt::Real, L; hbar::Real=1, heisenberg=true, truncation::Function=copy, gamma=[]))

Single step of Runge–Kutta-4 for solving the Lindblad equation

``\\dot{O}=i[H,O]+\\sum_i \\gamma_i \\left(L_i^\\dagger O L_i -\\frac{1}{2} \\{ L_i^\\dagger L_i, O\\} \\right)``

Returns O(t+dt).
`L` is a list of jump operators.
"""
function rk4_lindblad(H::AbstractOperator, O::AbstractOperator, dt::Real, L; hbar::Real=1, heisenberg=true, truncation::Function=copy, gamma=[])
    @assert length(gamma) == length(L) || length(gamma) == 0
    (length(gamma) == 0) && (gamma = ones(length(L)))
    f(H, O, s, hbar) = f_lindblad(H, O, s, hbar, L, gamma)
    return rk4(H, O, dt; hbar = hbar, heisenberg = heisenberg, truncation = truncation, f = f)
end
